Namespace: opennms-instance
Host: onmshs
TestDeploy: false
OpenNMS:
  Core:
    Path: /core
    ServiceName: opennms-core
    Image: opennms/horizon-stream-core
    Replicas: 1
    HttpPort: 8181
    SshPort: 8101
    GrpcPort: 8990
    Resources:
      Limits:
        Cpu: 2
        Memory: 4Gi
      Requests:
        Cpu: 2
        Memory: 2Gi
  API:
    Path: /api
    ServiceName: opennms-rest-server
    Image: opennms/horizon-stream-rest-server
    Replicas: 1
    Port: 8118
    Resources:
      Limits:
        Cpu: 2
        Memory: 2Gi
      Requests:
        Cpu: 1
        Memory: 1Gi
  UI:
    Path: /
    ServiceName: opennms-ui
    Image: opennms/horizon-stream-ui
    Replicas: 1
    Port: 8117
    Resources:
      Limits:
        Cpu: 1
        Memory: 500Mi
      Requests:
        Cpu: 100m
        Memory: 250Mi
  Minion:
    ServiceName: opennms-minion
    Image: opennms/minion:29.0.10
    Replicas: 1
    SshPort: 8201
    SnmpPort: 1162
    SyslogPort: 1514
    Resources:
      Limits:
        Cpu: 2
        Memory: 1Gi
      Requests:
        Cpu: 1
        Memory: 512Mi
  Notification: 
    ServiceName: opennms-notifications
    Image: opennms/horizon-stream-notification
    Replicas: 1
    Port: 8080
    Resources:
      Limits:
        Cpu: 1
        Memory: 500Mi
      Requests:
        Cpu: 100m
        Memory: 250Mi
Postgres:
  ServiceName: postgres
  Image: postgres
  Replicas: 1
  AdminPassword: notset
  OpenNMSPassword: notset
  KeycloakPassword: notset
  VolumeSize: 10Gi
Keycloak:
  Path: /auth
  Port: 8443
  ServiceName: onms-keycloak
  AdminUsername: keycloak-admin
  AdminPassword: notset
  UserUsername: user001
  UserPassword: notset
  Image: opennms/horizon-stream-keycloak:test
  RealmName: opennms
  UUID:
    RealmId: 00000000-0000-0000-0000-000000000000
    ClientId: 00000000-0000-0000-0000-000000000000
    BaseUserId: 00000000-0000-0000-0000-000000000000
    AdminUserId: 00000000-0000-0000-0000-000000000000
Grafana:
  Image: placeholder
Prometheus:
  Enabled: true
  Server:
    ServiceName: prometheus
    Port: 9090
    Image: prom/prometheus
    Replicas: 1
    Resources:
      Limits:
        Cpu: "1"
        Memory: 512Mi
      Requests:
        Cpu: 100m
        Memory: 100Mi
  PushGateway:
    ServiceName: prometheus-pushgateway
    Port: 9091
    Image: prom/pushgateway
    Replicas: 1
    Resources:
      Limits:
        Cpu: "1"
        Memory: 512Mi
      Requests:
        Cpu: 100m
        Memory: 100Mi
MailServer:
  ServiceName: mail-server
  Image: mailhog/mailhog:latest
  Replicas: 1 
  Port: 8025
  SmtpPort: 1025
  Resources:
    Limits:
      Cpu: 100m
      Memory: 200Mi
    Requests:
      Cpu: 100m
      Memory: 100Mi
ApiGateway:
  ServiceName: api-gateway
  Image: nginx:1.21.6-alpine
  Replicas: 1
  Port: 80
  Resources:
    Limits:
      Cpu: 100m
      Memory: 200Mi
    Requests:
      Cpu: 100m
      Memory: 100Mi