Namespace: opennms-instance
Host: onmshs
TestDeploy: false
OpenNMS:
  Core:
    Path: /core
    ServiceName: opennms-core
    Image: opennms/horizon-stream-core
    HttpPort: 8181
    SshPort: 8101
    GrpcPort: 8990
    Resources:
      Limits:
        Cpu: 2
        Memory: 4Gi
      Requests:
        Cpu: 2
        Memory: 2Gi
  API:
    Path: /api
    ServiceName: opennms-rest-server
    Image: opennms/horizon-stream-rest-server
    Resources:
      Limits:
        Cpu: 2
        Memory: 2Gi
      Requests:
        Cpu: 1
        Memory: 1Gi
  UI:
    Path: /
    ServiceName: opennms-ui
    Image: opennms/horizon-stream-ui
    Resources:
      Limits:
        Cpu: 2
        Memory: 2Gi
      Requests:
        Cpu: 1
        Memory: 1Gi
  Minion:
    ServiceName: opennms-minion
    Image: opennms/minion:29.0.10
    SshPort: 8201
    SnmpPort: 1162
    SyslogPort: 1514
    Resources:
      Limits:
        Cpu: 2
        Memory: 1Gi
      Requests:
        Cpu: 1
        Memory: 512Mi
Postgres:
  ServiceName: postgres
  Image: postgres
  AdminPassword: notset
  OpenNMSPassword: notset
  KeycloakPassword: notset
  VolumeSize: 10Gi
Keycloak:
  Path: /auth
  Port: 8443
  ServiceName: onms-keycloak
  AdminUsername: keycloak-admin
  AdminPassword: notset
  UserUsername: user001
  UserPassword: notset
  Image: opennms/horizon-stream-keycloak:test
  UUID:
    RealmId: 00000000-0000-0000-0000-000000000000
    ClientId: 00000000-0000-0000-0000-000000000000
    BaseUserId: 00000000-0000-0000-0000-000000000000
    AdminUserId: 00000000-0000-0000-0000-000000000000
Grafana:
  Image: placeholder
Prometheus:
  Enabled: true
  Server:
    ServiceName: prometheus
    Port: 9090
    Image: prom/prometheus
    Resources:
      Limits:
        Cpu: "1"
        Memory: 512Mi
      Requests:
        Cpu: 100m
        Memory: 100Mi
  PushGateway:
    ServiceName: prometheus-pushgateway
    Port: 9091
    Image: prom/pushgateway
    Resources:
      Limits:
        Cpu: "1"
        Memory: 512Mi
      Requests:
        Cpu: 100m
        Memory: 100Mi