Namespace: opennms-instance
Host: localhost
TestDeploy: false
OpenNMS:
  Core:
    Path: /core
    ServiceName: opennms-core
    Image: opennms/horizon-stream-core
    Resources:
      Limits:
        Cpu: 2
        Memory: 4Gi
      Requests:
        Cpu: 2
        Memory: 2Gi
  API:
    Path: /api
    ServiceName: opennms-rest-server
    Image: opennms/horizon-stream-rest-server
    Resources:
      Limits:
        Cpu: 2
        Memory: 2Gi
      Requests:
        Cpu: 1
        Memory: 1Gi
  UI:
    Path: /
    ServiceName: opennms-ui
    Image: opennms/horizon-stream-ui
    Resources:
      Limits:
        Cpu: 2
        Memory: 2Gi
      Requests:
        Cpu: 1
        Memory: 1Gi
Postgres:
  ServiceName: postgres
  Image: postgres:13.3-alpine
  AdminPassword: notset
  KeycloakPassword: notset
  VolumeSize: 10Gi
Keycloak:
  Path: /auth
  ServiceName: onms-keycloak
  AdminUsername: keycloak-admin
  AdminPassword: notset
  UserUseranme: user001
  UserPassword: notset
  Image: opennms/horizon-stream-keycloak:latest
  UUID:
    ClientId: 00000000-0000-0000-0000-000000000000
    BaseUserId: 00000000-0000-0000-0000-000000000000
    AdminUserId: 00000000-0000-0000-0000-000000000000
Grafana:
  Image: placeholder
Prometheus:
  Server:
    ServiceName: prometheus
    Image: prom/prometheus
  PushGateway:
    ServiceName: prometheus-pushgateway
    Image: prom/pushgateway
