site:
  title: Lōkahi/Cloud
  url: https://github.com/OpenNMS-Cloud/lokahi
  start_page: lokahi::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    tags:
      -v*
    start_path: docs
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v3.1.0/ui-bundle.zip
asciidoc:
  attributes:
    stem: latexmath
    tabs: tabs
  extensions:
    - ./docs/lib/tabs-block.js
output:
  clean: true
  dir: ./public
  destinations:
    - provider: fs
    - provider: archive
