Operator:
  image: opennms/operator:latest
  imagePullPolicy: Never
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 500Mi
TLS:
  Enabled: false

