apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: horizon-stream
build:
  artifacts:
  - image: opennms/horizon-stream-core
    context: platform
    custom:
      buildCommand: ../dev/skaffold-build.sh
      dependencies:
        paths: ["."]
        ignore: ["**/target/**"]
  - image: opennms/horizon-stream-api
    context: rest-server
    custom:
      buildCommand: ../dev/skaffold-build.sh
      dependencies:
        paths: ["src/**"]
        ignore: ["**/target/**"]

portForward:
  - resourceType: deployment
    resourceName: my-horizon-stream-api
    port: 9090
  - resourceType: deployment
    resourceName: my-horizon-stream-core
    port: 8181
    localPort: 18181
  - resourceType: deployment
    resourceName: my-horizon-stream-core
    port: 8101
    localPort: 18101
  - resourceType: deployment
    resourceName: my-horizon-stream-core
    port: 5005
    localPort: 15005
  - resourceType: deployment
    resourceName: my-keycloak
    port: 8080
    localPort: 28080

deploy:
  kubectl:
    manifests:
    - local-docker-compose/kubernetes.kafka.yaml
