name: 'Build and test keycloak-ui'
description: 'This implements unit and built-time integration tests on keycloak-ui.'
inputs:
  dir-location:
    description: 'The dir containing the change.'
    required: true
    default: 'none'

runs:
  using: "composite"
  steps:
    - name: build-image
      run: |

        cd ${{ inputs.dir-location }}

        # When there are tests to run, put those here.

        # Create the docker image.
        docker build -t opennms/horizon-stream-keycloak:local -f ./Dockerfile .
      shell: bash
    
    - name: dockerhub-login
      run: |
        echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
      shell: bash

    - name: publish-image-keycloak-ui
      run: |
        docker tag opennms/horizon-stream-keycloak:local opennms/horizon-stream-keycloak:test

        docker push opennms/horizon-stream-keycloak:test
      shell: bash