name: 'Test components in Kubernetes cluster'
description: 'This implements external integration test for all components. This is done in kubernetes cluster deployed in the runner.'
inputs:
  dir-location:
    description: 'The dir containing the change.'
    required: true
    default: 'none'

runs:
  using: "composite"
  steps:
    - name: Init
      run: |

        echo "For init - placeholder"
        # Confirm versions
        #java --version # JDK 11
        #docker version
        #kubectl -h

      shell: bash

    - name: Create Cluster
      run: |

        # Create cluster
        kind create cluster

        # Confirm cluster created
        kubectl config get-contexts
        kubectl get all

        docker ps
   
      shell: bash

    - name: Import Relevant Images into Cluster
      run: |

        # Check that the image was created.
        docker images
        # Image from the action-feature-core shows up here.

        kubectl get all

        docker ps

        kind load docker-image opennms/horizon-stream-ui:local          
        kind load docker-image opennms/horizon-stream-core:local        
        kind load docker-image opennms/horizon-stream-rest-server:local 

        # List images in kind cluster container.  
        # ISSUE: This produces an error, not required if the '$ kubectl apply
        # -f ...' succeeds below, means image loads were successful.
        #docker exec -it kind-control-plane crictl images ls

        cat dev/kubernetes.kafka.yaml|  sed 's/opennms\/horizon-stream-ui-dev/opennms\/horizon-stream-ui\:local/' > dev/kubernetes.kafka.1.yaml
        cat dev/kubernetes.kafka.1.yaml|  sed 's/opennms\/horizon-stream-api/opennms\/horizon-stream-rest-server\:local/' > dev/kubernetes.kafka.2.yaml
        cat dev/kubernetes.kafka.2.yaml|  sed 's/opennms\/horizon-stream-core/opennms\/horizon-stream-core\:local/' > dev/kubernetes.kafka.3.yaml

        kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.0/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
        kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.0/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
        kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.0/kubernetes/kubernetes.yml
        # Verify (should get keycloaks and keycloakrealmiiimports)
        kubectl api-resources | grep keycloak

        # Test change
        cat dev/kubernetes.kafka.3.yaml | grep image

        kubectl apply -f dev/kubernetes.kafka.3.yaml

        # Test install - Wait until core is running.
        sleep 60
        kubectl get all

        # TODO: Setup the portforward in background ('&') before running the
        # tools to create the user and pw to run. These are required to run the
        # Cucumber test.
        #cd tools
        #./KC.login -H localhost:28080 -u user001 -p passw0rd -R opennms
        #./events.list -H localhost:18181 -t "$(< data/ACCESS_TOKEN.txt)"
        #./events.publish -H localhost:18181 -t "$(< data/ACCESS_TOKEN.txt)"
        #./events.list -H localhost:18181 -t "$(< data/ACCESS_TOKEN.txt)"

      shell: bash

    - name: Run Cucumber Tests
      run: |

        # Install skaffold and run skaffold
        #
        # TODO: Push docker image (save tar or something) to cluster, if good, then run the docker push at end of this.
        #
        # TODO: Try this to test, but once the pipelines are up for creating
        # images for each of the sub dirs in horizon stream, cache them as
        # tar files and push them to the kind server and then update the
        # kubernetes yaml files here and apply them through kubectl. In this
        # way, we can remove skaffold and also use the docker images built
        # and tested in previous workflows.
        #curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
        #sudo install skaffold /usr/local/bin/
        #kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.0/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
        #kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.0/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
        #kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.0/kubernetes/kubernetes.yml
        ## Verify (should get keycloaks and keycloakrealmiiimports)
        #kubectl api-resources | grep keycloak
        #skaffold run --port-forward --skip-tests &
        #  # Run env
        #sleep 240
          # Wait for skaffold to deploy the horizon stream.

        # Test
        kubectl get all

        # Cucumber test - TODO
        cd ${{ inputs.dir-location }}

      shell: bash
