apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-env
  namespace: {{ .Release.Namespace }}
data:
{{- if .Values.OpenNMS.global.enableJsonLogging }}
  SPRING_PROFILES_ACTIVE: json-logging
{{- end }}
