apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Prometheus.Pushgateway.ServiceName }}
  labels:
    app: {{ .Values.Prometheus.Pushgateway.ServiceName }}
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.Prometheus.Pushgateway.ServiceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.Prometheus.Pushgateway.ServiceName }}
    spec:
      {{ if .Values.NodeRestrictions.Enabled }}
      tolerations:
        - effect: "NoSchedule"
          key: "{{ .Values.NodeRestrictions.Key }}"
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: "{{ .Values.NodeRestrictions.Key }}"
                    operator: In
                    values:
                      - {{ .Values.NodeRestrictions.Value }}
      {{ end }}
      containers:
        - name: {{ .Values.Prometheus.Pushgateway.ServiceName }}
          image: {{ .Values.Prometheus.Pushgateway.Image }}
          ports:
            - containerPort: 9091
          resources:
            limits:
              cpu: "2"
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 100Mi

