apiVersion: v1
kind: Service
metadata:
  labels:
    app: pebble
  name: {{ .Values.Pebble.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.Pebble.Port }}
      name: client
      protocol: TCP
      targetPort: {{ .Values.Pebble.Port }}
    - port: {{ .Values.Pebble.ControllerPort }}
      name: controller
      protocol: TCP
      targetPort: {{ .Values.Pebble.ControllerPort }}
  selector:
    app: {{ .Values.Pebble.ServiceName }}
  type: ClusterIP

