name: 'Maven Cache'
description: 'Caches Maven dependencies in the runner''s local Maven repository'
inputs:
  cache-key-path:
    description: 'Comma-separated file globs that reference files to use as the cache key'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: '~/.m2/repository'
        key: maven-deps-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(inputs.cache-key-path) }}
