apiVersion: v1
entries:
  opennms:
  - apiVersion: v2
    created: "2022-07-06T10:02:07.481093-04:00"
    digest: 6306ff0d5e059ea56fcdf26be5470a90408dcf71c975d137004261b6afacc837
    name: opennms
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-0.1.1.tgz
    version: 0.1.1
  opennms-operator:
  - apiVersion: v2
    created: "2022-07-06T10:02:07.481422-04:00"
    description: A Kubernetes operator for deploying and maintaining OpenNMS in the
      cloud.
    digest: 2004c4ba1b805007b2527fe3260d65fc2f2e917399cd41f44b2a5adcd88684ac
    home: https://github.com/OpenNMS/horizon-stream
    icon: https://www.opennms.com/wp-content/uploads/2021/04/OpenNMS_Horizontal-Logo_Light-BG-retina-website.png
    maintainers:
    - email: jkapp@opennms.com
      name: Jeffrey-David Kapp
    name: opennms-operator
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-operator-0.1.1.tgz
    version: 0.1.1
  opennms-operator-dependencies:
  - apiVersion: v2
    created: "2022-07-06T10:02:07.481537-04:00"
    digest: 5fd26a59231ab173a8b7b0b51e60575bf955fdc11615a3bd65b30da5690e074d
    name: opennms-operator-dependencies
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-operator-dependencies-0.1.0.tgz
    version: 0.1.0
generated: "2022-07-06T10:02:07.480365-04:00"
