server:
  port: 9090
spring:
  cache:
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=600s

# graphql
graphql:
  spqr:
    gui:
      enabled: true

# keycloak admin client properties
horizon-stream:
  core:
    url: http://localhost:8181

logging:
  file.path: /var/log/restServer
#spring doc
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    oauth:
      client_id: horizon-stream
  packages-to-exclude:
    - "io.leangen.graphql"
