server:
  port: 9090
  ssl:
    enabled: true
    key-alias: onms
    key-store: "/app/onms.keystore"
    key-store-type: jks
    key-store-password: opennmspw
    key-password: opennmspw

spring:
  cache:
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=600s

# graphql
graphql:
  spqr:
    gui:
      enabled: true
    base-packages:
      - org.opennms.horizon.shared.dto

# keycloak admin client properties
horizon-stream:
  core:
    url: http://localhost:8181

logging:
  file.path: /var/log/restServer

tsdb.url: http://localhost:59090/api/v1/query
