version: 2.1

orbs:
  path-filtering: circleci/path-filtering@0.0.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:2021.02


parameters:
  run-job-no-ops:
    type: boolean
    default: false
  run-job-dev:
    type: boolean
    default: false
  run-job-external-it:
    type: boolean
    default: false

jobs:

  dev:
    executor: docker-executor
    steps:
      - run:
          name: "Dev"
          command: |
            echo ""
            echo "==============================================================="
            echo " This is a dev/ dir test.
            echo "==============================================================="
            echo ""

workflows:
  version: 2

  dev:
    when: << pipeline.parameters.run-job-dev >>
    jobs:
      - dev:
          filters:
            branches:
              only:
                - develop
