apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: {{ .Values.Postgres.ServiceName }}
  namespace: {{ .Values.Namespace }}
stringData:
  adminUser: "pgadmin"
  adminPwd: "{{ .Values.Postgres.AdminPassword }}"
  opennmsUser: "opennms"
  opennmsPwd: "{{ .Values.Postgres.OpenNMSPassword }}"
  keycloakUser: "keycloak"
  keycloakPwd: "{{ .Values.Postgres.KeycloakPassword }}"
type: Opaque