apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: {{ .Values.Postgres.ServiceName }}
  namespace: {{ .Values.Namespace }}
stringData:
  adminUser: "opennms"
  adminPwd: "{{ .Values.Postgres.AdminPassword }}"
  keycloakUser: "keycloak"
  keycloakPwd: "{{ .Values.Postgres.KeycloakPassword }}"
  pagerdutyUser: "pagerduty"
  pagerdutyPwd: "{{ .Values.Postgres.PagerdutyPassword }}"
type: Opaque
