apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.OpenNMS.Core.ServiceName }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ .Values.OpenNMS.Core.ServiceName }}
    app.kubernetes.io/name: {{ .Values.OpenNMS.Core.ServiceName }}
  annotations:
    autoupdate: "true"
spec:
  replicas: {{ .Values.OpenNMS.Core.Replicas }}
  selector:
    matchLabels:
      app: {{ .Values.OpenNMS.Core.ServiceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.OpenNMS.Core.ServiceName }}
    spec:
      {{ if .Values.NodeRestrictions.Enabled }}
      tolerations:
        - effect: "NoSchedule"
          key: "{{ .Values.NodeRestrictions.Key }}"
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "{{ .Values.NodeRestrictions.Key }}"
                operator: In
                values:
                - {{ .Values.NodeRestrictions.Value }}
      {{ end }}
      terminationGracePeriodSeconds: 120
      containers:
        - name: {{ .Values.OpenNMS.Core.ServiceName }}
          image: {{ .Values.OpenNMS.Core.Image }}
          imagePullPolicy: {{ .Values.OpenNMS.Core.ImagePullPolicy }}
          args: [ "-f" ]
          env:
            - name: JAVA_TOOL_OPTIONS
              # value: "-Djava.security.egd=file:/dev/./urandom"
            - name: PGSQL_SERVICE_NAME
              value: {{ .Values.Postgres.ServiceName }}
            - name: PGSQL_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: adminUser
            - name: PGSQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: adminPwd
            - name: KAFKA_BROKER_HOST
              value: "{{ .Values.Kafka.URL }}"
            - name: KAFKA_BROKER_PORT
              value: "9092"
            - name: ACTIVEMQ_BROKER_URL #todo is this still needed?
              value: "tcp://localhost:61616"
            - name: KEYCLOAK_BASE_URL
              value: "http://{{ .Values.Keycloak.ServiceName }}:{{ .Values.Keycloak.Port }}"
            - name: KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: onms-keycloak-initial-admin
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onms-keycloak-initial-admin
                  key: password
            - name: PROMETHEUS_PUSHGATEWAY_URL
              value: "http://{{ .Values.Prometheus.PushGateway.ServiceName }}:{{ .Values.Prometheus.PushGateway.Port }}"
          volumeMounts:
            - name: config-volume
              mountPath: "/opt/horizon-stream/etc/org.opennms.horizon.alarmd.camel.cfg"
              subPath: "useKafka"
            - name: config-volume
              mountPath: "/opt/horizon-stream/etc/org.opennms.horizon.eventd.camel.cfg"
              subPath: "useKafka"
            - name: config-volume
              mountPath: "/opt/horizon-stream/etc/users.properties"
              subPath: "karafUsers"
              readOnly: true
          ports:
            - name: ssh
              containerPort: {{ .Values.OpenNMS.Core.SshPort }}
            - name: http
              containerPort: {{ .Values.OpenNMS.Core.HttpPort }}
            - name: grpc
              containerPort: {{ .Values.OpenNMS.Core.GrpcPort }}
          {{ if not .Values.TestDeploy }}
{{/*    TODO  livenessProbe:*/}}
{{/*          readinessProbe:*/}}
{{/*          startupProbe:*/}}
          {{ end }}
          resources:
            limits:
              cpu: "{{ .Values.OpenNMS.Core.Resources.Limits.Cpu }}"
              memory: "{{ .Values.OpenNMS.Core.Resources.Limits.Memory }}"
            requests:
              cpu: "{{ .Values.OpenNMS.Core.Resources.Requests.Cpu }}"
              memory: "{{ .Values.OpenNMS.Core.Resources.Requests.Memory }}"
      volumes:
        - name: config-volume
          configMap:
            name: opennms-config


