apiVersion: v1
kind: ConfigMap
metadata:
  name: opennms-config
  namespace: {{ .Values.Namespace }}
data:
  restCfg: |
    keycloak.base-url=http://{{ .Values.Keycloak.ServiceName }}:{{ .Values.Keycloak.Port }}{{ .Values.Keycloak.Path }}
    keycloak.admin-username={{ .Values.Keycloak.AdminUsername }}
    keycloak.admin-password={{ .Values.Keycloak.AdminPassword }}
  useKafka: |
    useSeda=false
    useKafka=true
    useActiveMq=false
  karafUsers: |
    admin=admin,_g_:admingroup
    _g_\:admingroup=group,admin,manager,viewer,systembundles,ssh
  application.yml: |
    server:
      port: 9090
      ssl:
        enabled: true
        key-alias: onms
        key-store: "/app/onms.keystore"
        key-store-type: jks
        key-store-password: opennmspw
        key-password: opennmspw

    spring:
      cache:
        caffeine:
          spec: maximumSize=10000,expireAfterWrite=600s

    # graphql
    graphql:
      spqr:
        gui:
          enabled: true
        base-packages:
          - org.opennms.horizon.shared.dto

    # keycloak admin client properties
    horizon-stream:
      core:
        url: http://localhost:{{ .Values.OpenNMS.Core.HttpPort }}

    logging:
      file.path: /var/log/restServer
binaryData: 
  # Just for backend SSL, can add dynamically at some point. This one is set
  # for a 1000 years roughly with CN as opennms-rest-server. Remove eventually
  onms.keystore: >-
    /u3+7QAAAAIAAAABAAAAAQAEb25tcwAAAYKTMouTAAAFATCCBP0wDgYKKwYBBAEqAhEBAQUABIIE6QM+7bW1mmV6ib2kQJvCXzOuhTFKLwm6PGljtTFFA5abpZ7qnryre+Nis2DDdWqSRl2YUqOP3gVHd5zOOKOdRYdOvBJ46OYd3SebYrujcErYWZr1NXcj9LSjPtyt+b2hGaCwvwP95m5szr3mwyhAmw4bDhb3qdazqTP8Xw+Pi4qKyn9SCh9tpOcQCR4S49moHqvpZ/3tHRsd0hktofpwoC1lGUF2kLAcNlzJKU3lPUNvw0nH2oGbwF1l+wESmehW4SNFWT4O98z2IonkK/yhrtn8Pv16AQ/xwfo9Bc3ghkwbX0fOfXIHPi76dAmn8woob8Je3ZnA+edkjTHjkyxa0RDdNq5KKOxeYbed4krOzkRdvjLjEo1w2PheIixPMSQFZ5i+EQB99dZuUjaXcdk4XnlS85rfqjfjv9igponxvJwB3hTBVjJLlqRPIlISwjwGMA7qg2ZT5FQoDgVZrPXBBk0bxv3WWB4AxgDgESrWT5GU20xWJ4mBNkApWmI2Z2m/0xeGW9+TlWCVehuOXdnF+W/HhXPqoCIMJ9QzAHr853wZDW40AKpAcbQFmojTQ3mKNe5e00KmB0Kx0mXj0HnVTKc9mAD9IHV+L29lroibHkXsnvsRDC3O/GaKZiU2fp+NDLXdqm4GyFkGs3Kurj35I5U64G2LgEQU1Mxh+byWuVNPDulTZMOUwzwXm1nnpFshXFvE3nZ+NVMiqpmk6QIf8MpCzDjRssVcNjCzM490aV/P5HIydZUajxTD6uW7hbQu+EtzcHcciQyuz5slTiCQmIzUPb8gPsM5EnhBZacyMZYMjQGsiYz7paJKWmUzapuD89kbRKMje9XzjBmlgb209yAU3dBxewVnsCacgQK8mjSMXQ3cI2QBs/fqil7of1loX5czJeZ6ZKhJ2z5mWvJGf2iC0hPkaLtX5vBpQZ56PEufHks4Tg9qwKnWrxB9QsW8jC5zFMG2o2+wypkQqGmsNSdGKT0PErzMkpNSyAYEZJdlYUaeWFEfSJ2ijLjLaYVXd+0VMLirl9QwuLMdrrDR3pGu+PSVyMr+VvKiqi5BUcJMZ9UWfAmHWfLZC2ePmOW6oQyWkSBtcykvWMX1YryZDsjXrDZjv4FUVdmuH66oAr4WkMh5PHDZwJ2UPmd/9PNcR4Fj3KvoibhHuxq1s9Hw1hbdcmBDpKKyS4Lym+oGL0kjrfIPO1c53j9naiXqFFS3ZvYIVJ4XBJ6gPZB9ev+V6fsfqFfRcYErefPeFYIzrremjvmmtkXMtnRVoIKCr+ltLl8ovnKxhF15DEFunqOXxgFGRkcd0q3V4+CBfQAVNh1B0TgrDEICh/ZPx26ucGmm4CumTOOOPtDGw1IKDuaFYEEcDfbrR/R0Uhefla4tDbVfkTZo/dJd3bN+YbDaKOaKEwsy0Ykos2O3UHF7rNiyGmT8N+HejFGygOsLK01zxYXSYcPqx6P9f1NuMO9Bqq6R4ITPiEeqwzxlPmCzywEwEw0spJCEXJzJGEIYVLW1SbOryccZy/nSke7xOFjC+VdkpfzVo7nhjRe0Viel4Tskjj/RaPCTwP6KfzdpOPPei3CPldBI/Mf+Xu+Jac3gMEwYa/qkF9VbfFMR+DJ350/fQIAQZZw/kes/KvsIEKC81gjCeO1BQ/KlRFpj5IAOSDcqcP2Y0ELGqVkEEQAAAAEABVguNTA5AAADgTCCA30wggJloAMCAQICBHzl6K0wDQYJKoZIhvcNAQELBQAwbjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkhJMREwDwYDVQQHEwhIb2x1YWxvYTEQMA4GA1UEChMHUGl2b3RhbDEPMA0GA1UECxMGU3ByaW5nMRwwGgYDVQQDExNvcGVubm1zLXJlc3Qtc2VydmVyMCAXDTIyMDgxMjE3NTUzOVoYDzMwMjExMjEzMTc1NTM5WjBuMQswCQYDVQQGEwJVUzELMAkGA1UECBMCSEkxETAPBgNVBAcTCEhvbHVhbG9hMRAwDgYDVQQKEwdQaXZvdGFsMQ8wDQYDVQQLEwZTcHJpbmcxHDAaBgNVBAMTE29wZW5ubXMtcmVzdC1zZXJ2ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCFj6s1ONEUpxcXh4PQFrN6xkCxwTZop0RzHqNThPZoI2IqH/oelIX66l/tc5sJRp5derqFVddNYtmyK7KJ/BzRNWPMO8Kx/KsMtRwkBaktsge41blQi1uzvTOJuUkk3HftLwoijrTl85YSFlMZ4uI4yeJ5RZIS7uEf2jbz51Cmv7hV1erjqvNTOnwJgTQu7XUAlmsCWfTRETfq5fE6MKmx72dg3b98lmvhbXoLOk8aRySFTzXVLQqymqE2z1JNqLsvCImma9lgWZaJb49MEg19CEBYR0Y13rJrOT/sSbtNByv2QWHOX1gpjx9e0rS/4nw4x9HnHfcircP7BRaSe3tDAgMBAAGjITAfMB0GA1UdDgQWBBSfRcE0qOpBNr0Qs3Pme8o54URTTjANBgkqhkiG9w0BAQsFAAOCAQEALCQqR4UN4T4GFJkvA8GI/DGP+OF11EnwPhKFwo+PZCMpXp9LXQ+mE84FF3iqLMJgXWrTxaNaErHvxg2SUXsG2KUPjHCWcgHHA6CSHdxFRSR6WttXuO3lrQBUdeFiZu73+zhB2w3D201uyz+KF4XybYkPIpi0MVrFIGUC9hi0EUj1ljlWWtn82WImmUWkCjQWnsspWhSHc0/g348WImE/0j/2J/FAivYrkmnsBW2i5Xzcsm953kgjf4E6CEFtx8kvgh6KHWH42YqnTm/7bT/Sa8B2ws8GnTgtDmS132B0kJ9GVOqvb3rp9f2AC7F5urCTK/ulmbLvDAMa/2CEt1GQlS+MYKYfPIFozd3h5nVljBD42vnu
  truststore.jks: >- 
    MIIEcwIBAzCCBCwGCSqGSIb3DQEHAaCCBB0EggQZMIIEFTCCBBEGCSqGSIb3DQEHBqCCBAIwggP+AgEAMIID9wYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBSBCIJ3NeP51QeTR0guHYfzqzu+PwICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEFF7aTB/ttb4DmrUXBhne32AggOADZR+59mCWdEhgKY/1vYPodNmZkfTpuR1Qnxh6KugIGI3dofHk9gsURXPrVg1ybIgBPWyPVdY79y7/igreKQ8AoppHvBicIzve+U+mqB+IyXp1wjucxD8vyOcOcZxllmzm8uJxxJ5JwwpvubQMoMaCpO7j6rGAuEPQXLYjESo78QF5/XPcqzCLS5Zsr3Cmjmh0Jyr9eIfqk+Z9pOgkfPaXOAf+V2pSXyaOO6vj1X1j5K2+/D35QHKGhCQwIosAW9+zMJtk615g14wMM6Iqe3TdvpI6IMYa1KLRTlqCHWHKcZ2pJlUSuQGVg6YfK18yCuFV98nbiGNOs+b9MOMy9FKi6ltquy5g4kFXIWli/wQeIhWlPSm03pdPwfG9oxB9tPjB0P5l9rwnMdXu4Mbbm4kQ0uVI+bn4WpKgvAVLg0AAcoYFYmq1InqU8WZBF5jwlbLmk3B0RYS2nbMBvqqwYftY4RzbiCob1RQBIOxrrQQnK0Cr2cBMyaQ5NfUQPO0jsK+L8TMb/qGsYOH+UPEfFf+g7/CyVtvoJuj14Qs9NaA4TMch1ZzBwsrdsRgpOiLdYvGGFreG3fZe0NnA7FUxF3KJo3BPwYNoX1ZXHyuK6s+n1jxmSWewbx2CW9E0mUYbVS7ewI4JpBLSJWTWzR4OnbzG00kw6Mu/7vR8X+FE9Fr9HUXLuE1iawKbHGVerSHdrZc0JCNz3+7YbqmfKootzEa5mjlh36PN8s12bmpkg5+6DYXJ3ZTn5yqE4eAYSONTUHTk6Gon6iFGojjL3PxOxBpcwNv9zxfs4+CC7SMg6KpX537mV6zGgfujiMpL6AEPoQhAnh5TLAEXXxV8dBUdVAXOZ9Vmvw4wENxG8F+OMOQj4TcAQj8qJbXlTiGNy4PQRQeobDuyk+28KAUpL3tacaND0lLDmrCS7FdFEqcisldVGUfjmIrdTPSXeceERHCLjhaJfovaWt/2AsxTjnblWdNezO7N0t1FAG6690gSWf6ZZqKK1uIBp1wXhLiEGXjujh2pKvKshG5aGiIX2LNpML8tJMlwBMkRGSmbAdIToEXL4Gcx5ROvstTIgfiVOlLNBow7/yxqlwL2fs8mTxTyRFdXRaK9p6HN38CY0x9voolnusBgyM9+oSUxyuFQlMQ0yVB5hO+YHltRRytAaUxQp1bztkiYvXtclAsyan9ck426y8wPjAhMAkGBSsOAwIaBQAEFKcgrgjb0rBXnBxeDdhd6V+99VvMBBRFDgF13mulys51X8i3guWrd4lVGAIDAYag

