{{- if .Values.Citus.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: citus
  namespace: {{ .Release.Namespace }}
  labels:
    app: citus
spec:
  selector:
    app: citus
  clusterIP: None
  ports:
  - port: 5432
    name: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: citus-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    app: citus
spec:
  selector:
    app: citus
  ports:
  - port: 5432
    name: postgres
    nodePort: {{ .Values.Citus.Nodeport }}
  type: NodePort
{{- end }}
