spring:
  application:
    name: horizon-stream-alarm

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/alarm
    username: alarm
    password: passw0rd

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: db/changelog/changelog.xml

  kafka:
    consumer:
      group-id: "alarm"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    bootstrap-servers: localhost:59092

kafka:
  topics:
    alarm-events: "alarm-events"
    new-alarms: "new-alarms"
