version: "2"

# TODO: POSTGRES username + password (NOT "trust")
services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
    ports:
      - 5432:5432
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  # WARNING: using developer-only mode for keycloak
  # TODO: use a separate database
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    command: [ "start-dev" ]
    environment:   
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=keycloak-admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgres-host
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=unused
    ports:
      - 28080:8080
      - 28443:8443
#    volumes:
#      - "keycloak_data:/opt/keycloak/data:rw"

  horizon-stream:
    image: opennms/horizon-stream-core:local
    command: [ "-f" ]
    ports:
      - "18101:8101"
      - "18181:8181"
      - "15005:5005"
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - PGSQL_SERVICE_NAME=postgres
      - PGSQL_ADMIN_USERNAME=postgres
      - PGSQL_ADMIN_PASSWORD=passw0rd
      - KAFKA_BROKER_HOST=kafka
      - KAFKA_BROKER_PORT=9092
      - ACTIVEMQ_BROKER_URL=tcp://localhost:61616
      - KEYCLOAK_BASE_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN_USERNAME=keycloak-admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

volumes:
  postgres_data:
    driver: local
  keycloak_data:
    driver: local
