version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "42181:2181"
    volumes:
      - "zookeeper_data:/bitnami/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=no
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=zookeeper-user
      - ZOO_SERVER_PASSWORDS=passw0rd
      - ZOO_CLIENT_USER=zookeeper-user
      - ZOO_CLIENT_PASSWORD=passw0rd

  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "39092:9092"
    volumes:
      - "kafka_data:/bitnami/kafka"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_USER=zookeeper-user
      - KAFKA_ZOOKEEPER_PASSWORD=passw0rd
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HOSTNAME=kafka
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CLIENT_USERS=kafka-user
      - KAFKA_CLIENT_PASSWORDS=passw0rd
    depends_on:
      - zookeeper

  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
    ports:
      - 5432:5432
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  # WARNING: using developer-only mode for keycloak
  # TODO: use a separate database
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    command: [ "start-dev" ]
    environment:   
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=keycloak-admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgres-host
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=unused
    ports:
      - 28080:8080
      - 28443:8443
#    volumes:
#      - "keycloak_data:/opt/keycloak/data:rw"

  # TODO: need to support passwords for Kafka clients
  horizon-stream:
    image: opennms/horizon-stream-core:local
    command: [ "-f" ]
    ports:
      - "18101:8101"
      - "18181:8181"
      - "15005:5005"
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - PGSQL_SERVICE_NAME=postgres
      - PGSQL_ADMIN_USERNAME=postgres
      - PGSQL_ADMIN_PASSWORD=passw0rd
      - KAFKA_BROKER_HOST=kafka
      - KAFKA_BROKER_PORT=9092
      - ACTIVEMQ_BROKER_URL=tcp://localhost:61616
      - KEYCLOAK_BASE_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN_USERNAME=keycloak-admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - "./data-kafka/horizon-stream/etc/org.opennms.horizon.alarmd.camel.cfg:/opt/horizon-stream/etc/org.opennms.horizon.alarmd.camel.cfg"


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  postgres_data:
    driver: local
  keycloak_data:
    driver: local
