apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Values.Keycloak.ServiceName }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: keycloak
spec:
  instances: 1
  hostname: {{ .Values.Host }}
  tlsSecret: {{ .Values.TLS.Cert.Name }}
  image: {{ .Values.Keycloak.Image }}
  disableDefaultIngress: true
  serverConfiguration:
    - name: db-url-host
      value: {{ .Values.Postgres.ServiceName }}
    - name: db-username
      secret:
        name: postgres
        key: keycloakUser
    - name: db-password
      secret:
        name: postgres
        key: keycloakPwd