apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Keycloak.ServiceName }}
  labels:
    app: keycloak
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.Keycloak.ServiceName }}
  replicas: {{ .Values.Keycloak.Replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.Keycloak.ServiceName }}
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.Keycloak.Image }}
          imagePullPolicy: {{ .Values.Keycloak.ImagePullPolicy }}
          resources:
            limits:
              cpu: "{{ .Values.Keycloak.Resources.Limits.Cpu }}"
              memory: "{{ .Values.Keycloak.Resources.Limits.Memory }}"
            requests:
              cpu: "{{ .Values.Keycloak.Resources.Requests.Cpu }}"
              memory: "{{ .Values.Keycloak.Resources.Requests.Memory }}"
          command: [ 'bash' ]
          args: [ '-c', 'source /vault/secrets/database-config.txt && bin/kc.sh --verbose start --import-realm' ]
          env:
            - name: KC_HOSTNAME
              value: "{{ .Values.Host }}"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: {{ .Values.Postgres.ServiceName }}
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: keycloakUser
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: keycloakPwd
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_BACKCHANNEL
              value: "false"
          ports:
            - name: http
              containerPort: {{ .Values.Keycloak.Port }}
            - name: https
              containerPort: {{ .Values.Keycloak.HttpsPort }}