apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Values.Keycloak.ServiceName }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: keycloak
spec:
  instances: 1
  hostname: {{ .Values.Host }}
  tlsSecret: {{ .Values.TLS.Cert.Name }}
  serverConfiguration:
    - name: db
        value: postgres
    - name: db-url-host
        value: {{ .Values.Postgres.ServiceName }}
    - name: db-username
        secret:
          name: postgres
          key: keycloakUser
    - name: db-password
        secret:
          name: postgres
          key: keycloakPwd