apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: {{ .Values.Namespace }}
stringData:
  adminPwd: "{{ .Values.Keycloak.AdminPassword }}"
  userPwd: "{{ .Values.Keycloak.UserPassword }}"
  clientId: "{{ .Values.Keycloak.UUID.ClientId }}"
  adminId: "{{ .Values.Keycloak.UUID.BaseUserId }}"
  userId: "{{ .Values.Keycloak.UUID.AdminUserId }}"
type: Opaque