apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Host }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: keycloak
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP

