name: 'Build and test core'
description: 'This implements unit and built-time integration tests on core, dir platform.'
inputs:
  dir-location:
    description: 'The dir containing the change.'
    required: true
    default: 'none'
  enable-sonar-scan:
    description: 'Enables code scanning with SonarCloud.'
    required: true
  github-token:
    description: 'GITHUB_TOKEN secret for the workflow so SonarCloud can get PR information. Required if enable-sonar-scan is true.'
    required: false
  sonar-token:
    description: 'SONAR_TOKEN secret to authenticate job with SonarCloud. Required if enable-sonar-scan is true.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Cache SonarCloud packages
      if: ${{ inputs.enable-sonar-scan == 'true' }}
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-${{ runner.arch }}-sonar

    - name: global data
      if: ${{ inputs.enable-sonar-scan == 'true' }}
      run: |
        echo "Testing actions - " ${{ inputs.dir-location }}

        netstat -ltan

        # Keep the input arg of the dir, if the process is the same for each
        # core, rest-server, and ui, we can make this like a generic function.

        # IMPORTANT: Check the .circleci/ original build.

        # Simple build - no Integration Tests
        #mvn install
        # For testing the pipeline, just run this without tests to get the
        # publish working with releasing working correctly. The test takes
        # 5mins roughly.
        # Release on 0.0.0 for now.

        # Full build, including docker image creation and Integration Tests
        mvn -Prun-it,coverage verify \
          -Dhttp.keepAlive=false \
          -Dmaven.wagon.http.pool=false \
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 \
          -Dmaven.wagon.http.retryHandler.count=3 \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY

          # Added extra args to deal with time out issue, see
          # https://github.com/actions/virtual-environments/issues/1499.

        # How do we trigger the unit tests?

        #docker images
        # The image, opennms-horizon-application-it-image, is just for the
        # integration tests, ignore.  

      working-directory: ${{ inputs.dir-location }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_PROJECT_KEY: 'opennms_horizon-stream_core'

    - name: global data
      if: ${{ inputs.enable-sonar-scan == 'false' }}
      run: |
        echo "Testing actions - " ${{ inputs.dir-location }}

        netstat -ltan

        # Keep the input arg of the dir, if the process is the same for each
        # core, rest-server, and ui, we can make this like a generic function.

        # IMPORTANT: Check the .circleci/ original build.

        # Simple build - no Integration Tests
        #mvn install
        # For testing the pipeline, just run this without tests to get the
        # publish working with releasing working correctly. The test takes
        # 5mins roughly.
        # Release on 0.0.0 for now.

        # Full build, including docker image creation and Integration Tests
        #mvn -Prun-it install
        mvn -Prun-it verify \
          -Dhttp.keepAlive=false \
          -Dmaven.wagon.http.pool=false \
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 \
          -Dmaven.wagon.http.retryHandler.count=3

          # Added extra args to deal with time out issue, see
          # https://github.com/actions/virtual-environments/issues/1499.

        # How do we trigger the unit tests?

        #docker images
        # The image, opennms-horizon-application-it-image, is just for the
        # integration tests, ignore.  

      working-directory: ${{ inputs.dir-location }}
      shell: bash
