name: 'Build and install parent-pom'
description: 'Build and install the parent POM which defines standard dependency versions across sub-projects'
inputs:
  dir-location:
    description: 'The dir containing the change.'
    required: true
    default: 'none'
  github-token:
    description: 'GITHUB_TOKEN secret for the workflow so SonarCloud can get PR information'
    required: true
  sonar-token:
    description: 'SONAR_TOKEN secret to authenticate job with SonarCloud'
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-${{ runner.arch }}-sonar

    - name: build-image
      run: |

        cd ${{ inputs.dir-location }}

        mvn clean install \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY

      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_PROJECT_KEY: 'opennms_horizon-stream_parent-pom'
