spring:
  application:
    name: horizon-stream-events

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/events
    username: events
    password: OpenNMS

  liquibase:
    change-log: db/changelog/changelog.xml
