name: 'Build and test ui'
description: 'This implements unit and built-time integration tests on ui, dir platform.'
inputs:
  dir-location:
    description: 'The dir containing the change.'
    required: true
    default: 'none'
  github-token:
    description: 'GITHUB_TOKEN secret for the workflow so SonarCloud can get PR information'
    required: true
  sonar-token:
    description: 'SONAR_TOKEN secret to authenticate job with SonarCloud'
    required: true

runs:
  using: composite
  steps:
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-${{ runner.arch }}-sonar

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: ui/yarn.lock

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: ui
      shell: bash

    - name: build-image
      run: |

        cd ${{ inputs.dir-location }}

        # When there are tests to run, put those here.

        # Create the docker image with BuildKit enabled.
        DOCKER_BUILDKIT=1 docker build -t opennms/horizon-stream-ui:local .
      shell: bash

    - name: Coverage Report
      run: yarn test:coverage:sonar
      working-directory: ui
      shell: bash

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: ui
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
