name: 'Build and test Operator'
description: 'This implements unit and built-time integration tests on the Operator, dir platform.'
inputs:
  dir-location:
    description: 'The dir containing the change.'
    required: true
    default: 'operator'

runs:
  using: "composite"
  steps:
    - name: test runner name check
      run: echo "runner name is ${{ runner.name }}"
      shell: bash

    - name: test runner name check
      if: ${{ runner.name == 'self-hosted' }}
      run: echo "self hosted runner!"
      shell: bash

    - name: Cache SonarCloud packages
      if: ${{ false }}
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-${{ runner.arch }}-sonar

    - name: Setup golang
      if: ${{ false }}
      uses: actions/setup-go@v3
      with:
        go-version-file: operator/go.mod
        cache-dependency-path: operator/go.sum

    - name: Copy charts
      run: make copy-charts
      working-directory: operator
      shell: bash

    - name: unit-test
      run: |
        cd ${{ inputs.dir-location }}

        #make unit-test
        echo "TODO - Get this working"

      shell: bash

    - name: build-image
      run: |

        cd ${{ inputs.dir-location }}

        # When there are tests to run, put those here.

        # Create the docker image.
        make local-docker
      shell: bash

    - name: Test Coverage
      if: ${{ false }}
      run: make coverage
      shell: bash
      working-directory: operator

    - name: SonarCloud Scan
      if: ${{ false }}
      uses: SonarSource/sonarcloud-github-action@v1.7
      with:
        projectBaseDir: operator
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
  
