name: 'Build and test Operator'
description: 'This implements unit and built-time integration tests on the Operator, dir platform.'
inputs:
  dir-location:
    description: 'The dir containing the change.'
    required: true
    default: 'operator'

runs:
  using: "composite"
  steps:
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-${{ runner.arch }}-sonar

    - name: Setup golang
      uses: actions/setup-go@v3

    - name: Copy charts
      run: make copy-charts
      working-directory: operator
      shell: bash

    - name: unit-test
      run: |
        cd ${{ inputs.dir-location }}

        #make unit-test
        echo "TODO - Get this working"

      shell: bash

    - name: build-image
      run: |

        cd ${{ inputs.dir-location }}

        # When there are tests to run, put those here.

        # Create the docker image.
        make local-docker
      shell: bash

    - name: Test Coverage
      run: make coverage
      shell: bash
      working-directory: operator

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: operator
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
  
