name: 'Build and test Minion'
description: 'This implements unit and built-time integration tests on minion, dir minion.'
inputs:
  dir-location:
    description: 'The dir containing the change.'
    required: true
    default: 'none'

runs:
  using: "composite"
  steps:
    - name: global data
      run: |
        echo "Testing actions - " ${{ inputs.dir-location }}

        netstat -ltan

        cd ${{ inputs.dir-location }}

        mvn install -Dtest=true -DfailIfNoTests=false -DskipITs=true -DskipTests=false -Ddocker.image=opennms/horizon-stream-minion:local -Ddocker.skipPush=false

      shell: bash
