apiVersion: opennms.k8s.opennms.com/v1alpha1
kind: OpenNMS
metadata:
  name: local-instance
spec:
  allowedUsers: []
  host: ignore-for-now-onmshs
  namespace: local-instance
  core:
    version: opennms/horizon-stream-core
    cpu: "0"
    mem: 100Mi
  api:
    version: opennms/horizon-stream-rest-server
    cpu: "0"
    mem: 100Mi
  ui:
    version: opennms/horizon-stream-ui
    cpu: "0"
    mem: 100Mi
  postgres:
    version: postgres:13.3-alpine
