apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: operator
profiles:
  - name: use-operator
    resourceSelector:
      allow:
        - groupKind: "OpenNMS.k8s.opennms.com"
          image: [ ".*" ]
          labels: [ ".*" ]
    build:
      artifacts:
        - image: opennms/operator
          docker:
            dockerfile: Dockerfile
    deploy:
      helm:
        releases:
          - name: opennms-operator
            namespace: opennms
            createNamespace: true
            chartPath: ../charts/opennms-operator
            artifactOverrides:
              Operator.image: opennms/operator
