# your helm chart values here
Operator:
  image: opennms/operator:bleeding
  resources:
    limits:
      cpu: 1
      memory: 500Mi
    requests:
      cpu: 1
      memory: 500Mi
TLS:
  Enabled: false
