apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opennms-ingress
  namespace: local-instance
spec:
  ingressClassName: nginx
  rules:
  - host: onmshs
    http:
      paths:
      - backend:
          service:
            name: opennms-ui
            port:
              number: 3000
        path: /
        pathType: Prefix
      - backend:
          service:
            name: opennms-core
            port:
              number: 8101
        path: /karaf
        pathType: Prefix
      - backend:
          service:
            name: opennms-core
            port:
              number: 8181
        path: /core
        pathType: Prefix
      - backend:
          service:
            name: opennms-rest-server
            port:
              number: 9090
        path: /api
        pathType: Prefix
  tls:
  - hosts:
    - onmshs
    secretName: tls-cert-wildcard
