---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hs-ui
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: localhostui
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hs-ui
            port:
              number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-keycloak
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: localhostkey
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hs-api
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: localhostapi
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: horizon-stream-api
            port:
              number: 8080
