name: develop

on:
  pull_request:
    types: [ labeled ]

# For now, we have put all steps into a single job, this will allow for just
# one vm to run. We use actions to factor out the functionality. If there is a
# requirement to create additional jobs, maybe to run concurrent jobs, then we
# can split them up later.

jobs:
  develop:
    # The label must be as follows and this is only ever run on the default branch.
    #if: ${{ ( github.event.label.name == 'actions-release' ) || ( github.event.pull_request.head.ref == github.event.repository.default_branch ) }}
    if: ${{ ( github.event.label.name == 'actions-develop' ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        # Is required to call actions.

      - name: init
        run: |

          echo "For init steps."
          #TAG=$(curl \
          #  https://api.github.com/repos/OpenNMS/horizon-stream/git/commits/${{github.event.pull_request.head.sha}} | \
          #  jq '.message' | \
          #  awk '{ print $2 }')
          TAG=$(echo ${{github.event.pull_request.title}} | awk '{ print $2 }')
          echo "test - $TAG."

          echo "current branch: ${{github.event.pull_request.head.ref}}"
          echo "default branch: ${{github.event.repository.default_branch}}"

          # Validate tag format
          # Format of PR name: RELEASE <tag> - <message>
          # Format of tag (change numbers or dev, but leave everything else): 
          #   v0.0.5-dev
          #   v0.0.5
          if [[ $TAG =~ ^v[0-9]+.[0-9]+.([0-9]+-[a-z]+|[0-9]+)$ ]]
          then
            echo "Valid format, proceed with test."
          else
            echo "Tag format is invalid."
            exit 1
          fi

          # Create tag, push, merge develop to release branch and push release.
          # We can save the merge until after the publishing is done, and do it
          # manually on the PR.
          git fetch
          #git --no-pager log --decorate --graph --all --oneline | head -100
          #git remote -v
          git branch
          git checkout develop
          git branch
          git pull
          git tag $TAG
          git push origin $TAG

      #- name: feature-ui
      #  id: action-feature-ui
      #  uses: ./.github/actions/ui
      #  with:
      #    dir-location: 'ui'

      #- name: feature-core
      #  id: action-feature-core
      #  uses: ./.github/actions/core
      #  with:
      #    dir-location: 'platform'

      #- name: feature-rest-server
      #  id: action-rest-server
      #  uses: ./.github/actions/rest-server
      #  with:
      #    dir-location: 'rest-server'

      #- name: external-it
      #  id: action-external-it
      #  uses: ./.github/actions/external-it
      #  with:
      #    dir-location: 'external-it'

