name: feature-keycloak-ui

on:
  pull_request:
    paths:
      - 'keycloak-ui/**'
  workflow_call:
    inputs:
      image:
        description: 'Name of the image to build'
        required: false
        type: string
      image-tag:
        description: 'Tag for the built image'
        required: false
        type: string

env:
  IMAGE: ${{ inputs.image-name || 'horizon-stream-keycloak' }}
  IMAGE_TAG: ${{ inputs.image-tag || github.sha }}
  IMAGE_REGISTRY: ghcr.io

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        # Is required to call actions.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: keycloak-ui
          tags: ${{ env.IMAGE_REGISTRY }}/${{github.actor}}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha
