name: feature-ui

on:
  pull_request:
    paths:
      - 'ui/**'
  workflow_call:
    inputs:
      image:
        description: 'Name of the image to build'
        required: false
        type: string
      image-tag:
        description: 'Tag for the built image'
        required: false
        type: string

env:
  IMAGE: ${{ inputs.image || 'horizon-stream-ui' }}
  IMAGE_TAG: ${{ inputs.image-tag || github.sha }}
  IMAGE_REGISTRY: ghcr.io

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        # Is required to call actions.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: ui/yarn.lock

      - name: 'Install dependencies'
        run: 'yarn install --frozen-lockfile'
        working-directory: 'ui'

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ui
          tags: ${{ env.IMAGE_REGISTRY }}/${{github.actor}}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha

      - name: 'Coverage Report'
        run: 'yarn test:coverage:sonar'
        working-directory: 'ui'

      - name: 'SonarCloud Scan'
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
