name: feature-grafana

on:  
  push:
    branches:
      - '**'
      - '!develop'
      - '!release/**'
    paths:
      - 'keycloak-ui/**'

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        # Is required to call actions.

      - name: init
        run: |

          echo "For init steps."

      - name: feature-keycloak-ui
        id: action-feature-keycloak-ui
        uses: ./.github/actions/keycloak-ui
        with:
          dir-location: 'keycloak-ui'
