name: feature-minion-gateway

on:  
  push:
    branches:
      - '**'
      - '!develop'
      - '!release'
    paths:
      - 'minion-gateway/**'

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: init
        run: |

          echo "For init steps."

      - name: parent-pom
        id: action-parent-pom
        uses: ./.github/actions/parent-pom
        with:
          dir-location: 'parent-pom'

      - name: shared-lib
        id: action-shared-lib
        uses: ./.github/actions/shared-lib
        with:
          dir-location: 'shared-lib'

      - name: feature-minion-gateway
        id: action-feature-minion-gateway
        uses: ./.github/actions/minion-gateway
        with:
          dir-location: 'minion-gateway'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
