name: dev

on:  
  push:
    paths:
      - 'dev/**'

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - if:  ${{ github.ref == 'refs/heads/develop' }}
      run: |
        mkdir -p path/to/artifact
        echo hello > path/to/artifact/world.txt
    
    - if:  ${{ github.ref == 'refs/heads/develop' }}
      uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: path/to/artifact

  test-dev:
    needs: build-dev
    # VM to run container on.
    runs-on: ubuntu-latest
    #container:
    #  image: rancher/k3s:latest
    #  options: --env=K3S_TOKEN=300511717113269 --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin/aux --env=CRI_CONFIG_FILE=/var/lib/rancher/k3s/agent/etc/crictl.yaml --privileged
    #  #volumes:
    #  #  - /etc:/etc

    steps:
      - run: |
          echo "test: " ${{ github.workspace }}
          pwd
          ls
          #printf "ID=debian\n" > /etc/os-release
          cat /etc/*release | grep ^ID
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact
      - if:  ${{ github.ref == 'refs/heads/develop' }}
        run: cat path/to/artifact/world.txt

      # The container does not have git installed and is a scratch image.
      #- name: Check out repository code
      #  uses: actions/checkout@v2
      - name: Dev Test
        if:  ${{ github.ref == 'refs/heads/develop' }}
        run: |
          #/bin/k3s server &
          #/bin/k3s agent &
          #ps
          #sleep 20
          ## This starts the server.
          #echo "This runs if branch is develop."
          #ls -1
          #pwd
          #echo "just seeing what is happening"
          #kubectl get all
          docker version
          kubectl -h
